In [1]:
import pandas as pd
import numpy as np
import json

In [9]:
with open("FrequentFlyerForum-Profiles.json") as f:
    jsn = json.load(f)

In [216]:
isHeader = True
for profile in jsn['Forum Profiles']:
    df1 = pd.json_normalize(profile, record_path=['Registered Flights'], 
                           meta = ['Sex', 'NickName', ['Real Name', 'Last Name'], ['Real Name', 'First Name']]
                          )
    df2 = pd.json_normalize(profile, record_path=['Travel Documents'], meta = ['NickName'], meta_prefix=['Travel Documents'])
    
    df3 = pd.json_normalize(profile, record_path=['Loyality Programm'], meta = ['NickName'], meta_prefix=['Travel Documents'])
    
    df1 = pd.merge(df1, df2, on='NickName', how='left')
    df1 = pd.merge(df1, df3, on='NickName', how='left')
    if isHeader:
        df1.to_csv('FrequentFlyerForum-Profiles.csv', mode = 'w', index=False)
    else:
        df1.to_csv('FrequentFlyerForum-Profiles.csv', mode = 'a', header=False, index=False)
    isHeader = False

In [3]:
data = pd.read_csv('FrequentFlyerForum-Profiles.csv')

In [14]:
data.isna().mean()*100

Date                      0.000000
Codeshare                 0.000000
Flight                    0.000000
Arrival.City              0.000000
Arrival.Airport           0.000000
Arrival.Country           0.409174
Departure.City            0.000000
Departure.Airport         0.000000
Departure.Country         0.386554
Sex                      24.603120
NickName                  0.000000
Real Name.Last Name      49.623798
Real Name.First Name     49.623798
Passports               100.000000
Status                    9.566074
programm                  9.566074
Number                    9.566074
dtype: float64

In [3]:
pd.read_csv('BoardingData.csv', sep=';')

,PassengerFirstName,PassengerSecondName,PassengerLastName,PassengerSex,PassengerBirthDate,PassengerDocument,BookingCode,TicketNumber,Baggage,FlightDate,FlightTime,FlightNumber,CodeShare,Destination
0,SAVELII,VIKTOROVICH,RUSANOV,Male,03/10/1983,2879 096860,FRNINO,6625956945991971,Transit,2017-03-22,06:05,SU1369,Own,Moscow
1,LEV,MARKOVICH,ISAEV,Male,12/13/1975,1788 173211,Not presented,1643715499224676,Registered,2017-03-18,22:10,SU1180,Own,Volgograd
2,NIKOLAI,I.,NIKOLSKII,Male,12/26/1990,4396 926588,VWNYGF,6247422701565929,Transit,2017-03-18,22:10,SU1180,Own,Volgograd
3,ANATOLII,PETROVICH,SHILOV,Male,05/24/1997,2595 919752,WQFFUE,Not presented,Registered,2017-03-18,22:10,SU1180,Own,Volgograd
4,MIROSLAVA,VIACHESLAVOVNA,SEMENOVA,Female,01/31/1976,6775 516990,Not presented,Not presented,Registered,2017-03-12,11:45,SU6284,Own,Moscow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155142,RAMIL,S.,DOROFEEV,Male,02/14/1994,3256 077151,SNRBXU,8653871661040452,Delayed,2017-05-18,06:30,SU1158,Own,Rostov
155143,RUSLAN,KONSTANTINOVICH,CHISTIAKOV,Male,02/14/1975,3497 458395,Not presented,0223584175158947,None,2017-05-18,06:30,SU1158,Own,Rostov
155144,SOFIA,VALEREVNA,KALMYKOVA,Female,12/17/1972,6618 352713,Not presented,Not presented,Registered,2017-10-02,07:30,SU5614,Own,Petropavlovsk
155145,VIACHESLAV,F.,KONONOV,Male,05/20/2000,4567 242088,Not presented,0975693658645383,Registered,2017-09-16,07:00,SU1640,Own,Omsk
155146,ESENIIA,DANILOVNA,BLINOVA,Female,03/07/1984,2861 762272,Not presented,Not presented,None,2017-05-09,07:00,SU1279,Own,Moscow